openapi: '3.0.2'
info:
  title: API Documentation
  description: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
security:
  - bearerAuth: []
paths:
  /test:
    get:
      description: Test Message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
