npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${GH_TOKEN-fallback}
  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN-fallback}

npmScopes:
  chinaza:
    npmAlwaysAuth: true
    npmRegistryServer: https://npm.pkg.github.com
    npmPublishRegistry: https://npm.pkg.github.com
    npmAuthToken: ${GH_TOKEN-fallback}
  promind:
    npmAlwaysAuth: true
    npmRegistryServer: https://registry.npmjs.org
    npmPublishRegistry: https://registry.npmjs.org
    npmAuthToken: ${NPM_TOKEN-fallback}

nodeLinker: node-modules
