npmRegistries:
  //npm.pkg.github.com/:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN-fallback}

npmScopes:
  chinaza:
    npmRegistryServer: https://npm.pkg.github.com

nodeLinker: node-modules
