name: Publish Honey to NPM registry

permissions:
  contents: write
  packages: write
  pull-requests: write
  id-token: write # Required for OIDC

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  number_of_files_changeset_folder: 0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org" # Critical: enables OIDC auth wiring
          package-manager-cache: false # Recommended for release builds

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Enable Corepack
        run: corepack enable

      - run: yarn install

      - run: yarn test

      - run: yarn build

      - name: Change package name for NPM
        run: |
          jq '.name = "@promind/honey" | .publishConfig = {"access": "public"}' package.json > temp.json && mv temp.json package.json

      - name: Publish to NPM
        run: npm publish
